FASTTEXT_EMBEDDIG_PATH = "embedding/wiki.en.bin"
#Dimension of the word embeddings.
EMB_DIMENSION_SIZE = 300
#Embedding size of AutoEncoder embedding
AE_EMB_DIMENSION_SIZE = 150
NUM_EPOCHS = 50 
BATCH_SIZE = 256
RANDOM_SEED = 1234
LEARNING_RATE = 1e-3
CTT_BINARY_THRESHOLD=0.9
CTT_EMBEDDING_THRESHOLD=0.9
SIF_EMBEDDING_THRESHOLD=0.3
